[2024-03-07T05:33:38.902+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T05:32:11.162916+00:00 [queued]>
[2024-03-07T05:33:38.915+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T05:32:11.162916+00:00 [queued]>
[2024-03-07T05:33:38.915+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-03-07T05:33:39.001+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Extraçao_dos_dados> on 2024-03-07 05:32:11.162916+00:00
[2024-03-07T05:33:39.010+0000] {standard_task_runner.py:60} INFO - Started process 7088 to run task
[2024-03-07T05:33:39.017+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Extraçao_dos_dados', 'manual__2024-03-07T05:32:11.162916+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmp29ivf931']
[2024-03-07T05:33:39.021+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask Extraçao_dos_dados
[2024-03-07T05:33:39.116+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T05:32:11.162916+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T05:33:39.291+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Extraçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T05:32:11.162916+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T05:32:11.162916+00:00'
[2024-03-07T05:33:49.756+0000] {warnings.py:109} WARNING - /opt/***/dags/scrap/main.py:50: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 50 of the file /opt/***/dags/scrap/main.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(data)

[2024-03-07T05:33:59.795+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-07T05:33:59.799+0000] {process_utils.py:131} INFO - Sending 15 to group 7088. PIDs of all processes in the group: [7088]
[2024-03-07T05:33:59.800+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 7088
[2024-03-07T05:33:59.802+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-07T05:34:08.080+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-07T05:34:08.095+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Extraçao_de_dados_do_linkedin, task_id=Extraçao_dos_dados, execution_date=20240307T053211, start_date=20240307T053338, end_date=20240307T053408
[2024-03-07T05:34:08.267+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=7088, status='terminated', exitcode=0, started='05:33:38') (7088) terminated with exit code 0
