[2024-03-04T19:04:17.951+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:04:16.801105+00:00 [queued]>
[2024-03-04T19:04:17.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:04:16.801105+00:00 [queued]>
[2024-03-04T19:04:17.962+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-04T19:04:18.011+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): Extraçao_dos_dados> on 2024-03-04 19:04:16.801105+00:00
[2024-03-04T19:04:18.050+0000] {standard_task_runner.py:60} INFO - Started process 793 to run task
[2024-03-04T19:04:18.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Extraçao_dos_dados', 'manual__2024-03-04T19:04:16.801105+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmpkpf64v75']
[2024-03-04T19:04:18.056+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask Extraçao_dos_dados
[2024-03-04T19:04:18.155+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:04:16.801105+00:00 [running]> on host 46342418dab4
[2024-03-04T19:04:18.436+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Extraçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T19:04:16.801105+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-04T19:04:16.801105+00:00'
[2024-03-04T19:04:18.438+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-04T19:04:18.439+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source airf/env/Scripts/activate && uvicorn dags.app:app --reload']
[2024-03-04T19:04:18.451+0000] {subprocess.py:86} INFO - Output:
[2024-03-04T19:04:18.453+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: airf/env/Scripts/activate: No such file or directory
[2024-03-04T19:04:18.454+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-04T19:04:18.465+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-04T19:04:18.469+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Extraçao_de_dados_do_linkedin, task_id=Extraçao_dos_dados, execution_date=20240304T190416, start_date=20240304T190417, end_date=20240304T190418
[2024-03-04T19:04:18.523+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task Extraçao_dos_dados (Bash command failed. The command returned a non-zero exit code 1.; 793)
[2024-03-04T19:04:18.547+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T19:04:18.564+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
