[2024-03-07T00:59:40.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T00:58:47.792435+00:00 [queued]>
[2024-03-07T00:59:40.175+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T00:58:47.792435+00:00 [queued]>
[2024-03-07T00:59:40.176+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-07T00:59:40.250+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Extraçao_dos_dados> on 2024-03-07 00:58:47.792435+00:00
[2024-03-07T00:59:40.262+0000] {standard_task_runner.py:60} INFO - Started process 2945 to run task
[2024-03-07T00:59:40.276+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Extraçao_dos_dados', 'manual__2024-03-07T00:58:47.792435+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmpah3igbgc']
[2024-03-07T00:59:40.286+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask Extraçao_dos_dados
[2024-03-07T00:59:40.497+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-07T00:58:47.792435+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T00:59:41.215+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Extraçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:58:47.792435+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-07T00:58:47.792435+00:00'
[2024-03-07T00:59:41.218+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_exemplo.py", line 25, in extract
    test()
  File "/opt/airflow/dags/scrap/main.py", line 16, in test
    option = selenium.webdriver.ChromeOptions()
AttributeError: module 'selenium' has no attribute 'webdriver'
[2024-03-07T00:59:41.255+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Extraçao_de_dados_do_linkedin, task_id=Extraçao_dos_dados, execution_date=20240307T005847, start_date=20240307T005940, end_date=20240307T005941
[2024-03-07T00:59:41.306+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task Extraçao_dos_dados (module 'selenium' has no attribute 'webdriver'; 2945)
[2024-03-07T00:59:41.332+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-07T00:59:41.354+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
