[2024-03-07T01:00:51.693+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin-2.Extraçao_dos_dados scheduled__2024-03-05T07:00:00+00:00 [queued]>
[2024-03-07T01:00:51.708+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin-2.Extraçao_dos_dados scheduled__2024-03-05T07:00:00+00:00 [queued]>
[2024-03-07T01:00:51.709+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-07T01:00:51.786+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Extraçao_dos_dados> on 2024-03-05 07:00:00+00:00
[2024-03-07T01:00:51.827+0000] {standard_task_runner.py:60} INFO - Started process 2968 to run task
[2024-03-07T01:00:51.831+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin-2', 'Extraçao_dos_dados', 'scheduled__2024-03-05T07:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmpqg7mq06c']
[2024-03-07T01:00:51.835+0000] {standard_task_runner.py:88} INFO - Job 73: Subtask Extraçao_dos_dados
[2024-03-07T01:00:51.932+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin-2.Extraçao_dos_dados scheduled__2024-03-05T07:00:00+00:00 [running]> on host 4fca1e22de4a
[2024-03-07T01:00:52.098+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin-2' AIRFLOW_CTX_TASK_ID='Extraçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-05T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-05T07:00:00+00:00'
[2024-03-07T01:00:52.099+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_exemplo.py", line 25, in extract
    test()
  File "/opt/airflow/dags/scrap/main.py", line 16, in test
    option = selenium.webdriver.ChromeOptions()
AttributeError: module 'selenium' has no attribute 'webdriver'
[2024-03-07T01:00:52.126+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Extraçao_de_dados_do_linkedin-2, task_id=Extraçao_dos_dados, execution_date=20240305T070000, start_date=20240307T010051, end_date=20240307T010052
[2024-03-07T01:00:52.175+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 73 for task Extraçao_dos_dados (module 'selenium' has no attribute 'webdriver'; 2968)
[2024-03-07T01:00:52.206+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-07T01:00:52.230+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
