[2024-03-04T19:01:41.864+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:01:40.026882+00:00 [queued]>
[2024-03-04T19:01:41.876+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:01:40.026882+00:00 [queued]>
[2024-03-04T19:01:41.877+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-04T19:01:41.939+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): Extraçao_dos_dados> on 2024-03-04 19:01:40.026882+00:00
[2024-03-04T19:01:41.946+0000] {standard_task_runner.py:60} INFO - Started process 749 to run task
[2024-03-04T19:01:41.949+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Extraçao_de_dados_do_linkedin', 'Extraçao_dos_dados', 'manual__2024-03-04T19:01:40.026882+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_exemplo.py', '--cfg-path', '/tmp/tmptacmci4y']
[2024-03-04T19:01:41.951+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask Extraçao_dos_dados
[2024-03-04T19:01:42.035+0000] {task_command.py:423} INFO - Running <TaskInstance: Extraçao_de_dados_do_linkedin.Extraçao_dos_dados manual__2024-03-04T19:01:40.026882+00:00 [running]> on host 46342418dab4
[2024-03-04T19:01:42.380+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extraçao_de_dados_do_linkedin' AIRFLOW_CTX_TASK_ID='Extraçao_dos_dados' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T19:01:40.026882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-04T19:01:40.026882+00:00'
[2024-03-04T19:01:42.382+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-04T19:01:42.384+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'source env/Scripts/activate && uvicorn dags.app:app --reload']
[2024-03-04T19:01:42.442+0000] {subprocess.py:86} INFO - Output:
[2024-03-04T19:01:42.526+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: env/Scripts/activate: No such file or directory
[2024-03-04T19:01:42.527+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-04T19:01:42.536+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-04T19:01:42.539+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Extraçao_de_dados_do_linkedin, task_id=Extraçao_dos_dados, execution_date=20240304T190140, start_date=20240304T190141, end_date=20240304T190142
[2024-03-04T19:01:42.571+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task Extraçao_dos_dados (Bash command failed. The command returned a non-zero exit code 1.; 749)
[2024-03-04T19:01:42.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T19:01:42.617+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
